### ISSUE TITLE
Change where existing release details (stable release/head commit) are retrieved for cncf.ci 

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#103]
Feature: Change where existing release details (stable release/head commit) are retrieved for cncf.ci 
---

## Short Description: 
- change where release details are added/updated
- to increase collaboration with CNCF project maintainers
- to allow CNCF project maintainers to add release details on cncf.ci
- to allow CNCF project maintainers to modify release details on cncf.ci

## Tasks: 
- [x] Planning
- [x] Implement updates to where release details are added/updated
   - [x] Global Configuration Tasks:
   - [x] Trigger Client Tasks:
   - [x] Status Repo Tasks
   - [x] Per Project Sub-Repo(s) Tasks
   - [x] Dashboard updater Tasks
- [x]  Promote to staging to QA
- [x]  Promote to production 

## Documentation:
- [x] Update [CONTRIBUTING.md](https://github.com/crosscloudci/crosscloudci/blob/master/CONTRIBUTING.md) with instructions on how CNCF Project maintainers can update release details

**Comment by lixuna** [comment]
instructions added to https://github.com/crosscloudci/crosscloudci/blob/master/CONTRIBUTING.md#updating-release-details
