### ISSUE TITLE
EPIC: Add support for testing projects on ARM (on Packet)

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#122]
_From @lixuna on February 27, 2019 15:30_

**Feature Name:** 

- Add support for testing projects on Arm (on Packet)

**Short Description:** 

- Add Arm support to Packet test environment on cncf.ci
- Deploy projects and run project tests on Arm based instances
   * https://www.packet.com/hardware/arm/

Tasks:
---

- [x] Break down EPIC "Add support for testing projects on Arm (on Packet)" into incremental components

- [x] Create tickets to track status of:
  - [x] Add Arm support to Kubernetes (stable and head) #126
  - [x] Add Arm support to CNCF Graduated project: Prometheus #135 
  - [x] Add Arm support to CNCF Graduated project: CoreDNS #133 
  - [x] Add Arm support to CNCF Graduated project: Envoy #134 
  - [x] Add Arm support to CNCF Incubating project: Fluentd #136 
  - [ ] Add Arm support to CNCF Incubating project: Linkerd #137 
 

_Copied from original issue: vulk/cncf_ci#117_
