### ISSUE TITLE
[Release update] enable Kubernetes's latest stable release

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#138]
**Feature Name:** 

- [Release update] enable Kubernetes's latest stable release

**Short Description:** 

- 

**Location/URL:** 

- x.cncf.ci

**Design Mocks:** 
- N/A

---
---

## Tasks:
* [x]  update cross-cloud yml file with new release
* [x]  update K8s build stage
   * [x]  update for amd64 
   * [x]  update for arm64 
* [x]  update K8s provision stage
   * [x]  update for amd64 
   * [x]  update for arm64

**Comment by lixuna** [comment]
K8s v 1.16.2 promoted to cncf.ci in v3.0.0 on Fri, Oct 18, 2019
- https://github.com/crosscloudci/crosscloudci/wiki/CNCF-CI-v3.0.0-Release-Notes

<img width="494" alt="Screenshot 2019-10-21 09 28 25" src="https://user-images.githubusercontent.com/11701267/67216493-ed420580-f3e8-11e9-85be-e637b7a6c880.png">
