### ISSUE TITLE
[EPIC] Styling updates on cncf.ci 

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#139]
[EPIC] Styling updates on cncf.ci 
---
- [x] Update logos on cncf.ci
- [x] Update Header on cncf.ci
- [x] Update horseshoe lines on desktop
- [x] Test environment outline should have rounded corners
- [x] Test environment outline should not overlap text "Test environment" on small screens
- [x] responsive separating lines between projects break between 1024 pixels and the smaller mobile view
- [x]  Height of footer on is taller than expected
- [x]  on mobile, add a separator line above first project, ie. CoreDNS
- [x]  on mobile, in expanded project view, when any button (Stable/Head github, status badges) are pressed, I would expect to see expanded project view still open when i return to cncf.ci 
- [ ]  [Enhancement request] Separate dropdown list for architecture selection
