### ISSUE TITLE
[04-24-2019] Update URLs for all logos -- logos are showing as broken

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#144]
**Feature Name:** 

- Update URLs for all logos -- logos are showing as broken

**Short Description:** 

- logos are displaying as a "broken icon" on cncf.ci 
- Replace all logos on cncf.ci with updated versions from https://github.com/cncf/artwork

Projects:
  - K8s
  - CoreDNS
  - Envoy
  - Prometheus
  - Linkerd
  - fluentd
  - ONAP 

Header:
- CNCF 

### Tasks: 

- [x] Update logo for K8s > https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.svg
- [x] Update logo for CoreDNS > https://raw.githubusercontent.com/cncf/artwork/master/projects/coredns/icon/color/coredns-icon-color.svg
- [x] Update logo for Envoy > https://raw.githubusercontent.com/cncf/artwork/master/projects/envoy/icon/color/envoy-icon-color.svg
- [x] Update logo for Prometheus > https://raw.githubusercontent.com/cncf/artwork/master/projects/prometheus/icon/color/prometheus-icon-color.svg
- [x] Update logo for Linkerd > https://raw.githubusercontent.com/cncf/artwork/master/projects/linkerd/icon/color/linkerd-icon-color.svg
- [x] Update logo for  fluentd > https://raw.githubusercontent.com/cncf/artwork/master/projects/fluentd/icon/color/fluentd-icon-color.svg
- [x] Update logo for ONAP - no change

Header:
- [x] Update logo for CNCF > https://raw.githubusercontent.com/cncf/artwork/master/other/cncf/horizontal/color/cncf-color.svg

QA/Promotion:
- [x] Promote to master
  - [x] QA on dev

- [x] Promote to staging
   - [x] QA on staging
 
- [x] Promote to production
   - [x] QA on production

- [x] Close ticket
