### ISSUE TITLE
EPIC - Add "Linkerd 2.x" to cncf.ci

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#151]
**Feature Name:** 

- Add Linkerd2 to cncf.ci

**Short Description:** 

-  Currently, https://cncf.ci/ is pointed at https://github.com/linkerd/linkerd
-  Kiersten at Buoyant requested that cncf.ci be pointed at linkerd 2:
   - https://github.com/linkerd/linkerd2/
   - https://github.com/linkerd/linkerd2/releases/tag/stable-2.3.2 (or from whatever most recent `tag/*`)
 
Tasks: 

- [x]  planning
- [x]  implementation
   - [x] remove Linkerd project from cncf.ci - confirmed
   - [x] add Linkerd2 integration https://github.com/linkerd/linkerd2 to cncf.ci - confirmed
   - [x]  update Project details: name, logo, caption, GitHub URL
               - [ ]  Name: `Linkerd 2.x` - confirmed
               - [ ]  Logo: no change, same as Linkerd - confirmed
               - [ ]  Caption: no change, "Service Mesh" - confirmed
               - [ ]  GitHub URL: https://github.com/linkerd/linkerd2 - confirmed
     - [x]  update Release details: Stable release URL, head release URL
               - [ ]  Stable release: https://github.com/linkerd/linkerd2/releases/tag/stable-2.3.2 - confirmed
               - [ ]  head commit (master branch): https://github.com/linkerd/linkerd2/commits/master - confirmed
     - [x]  update Build phase   
     - [ ]  update app-deploy phase
- [x]  QA
- [x]  promote to production

**Comment by lixuna** [comment]
Confirmation of requirements: 
---

1. Would you like us to remove Linkerd 1.x from cncf.ci and replace it with Linkerd 2.x?
- Answer: Yes, that's right

2. What name would you like us to use on cncf.ci for Linkerd 2.x? 
  - For example, we can keep it listed as "Linkerd" or update the project name to "Linkerd2" or "Linkerd 2.x"
- Answer: Linkerd 2.x

3. We will use the same logo as Linkerd for Linkerd2 on cncf.ci, as listed on the CNCF Artwork directory
- Answer: Yes, same logo

4. We will use the same caption as Linkerd for Linkerd2, as "Service Mesh"
- Answer: Yes, that's right

5. We will update the GitHub URL from https://github.com/linkerd/linkerd to https://github.com/linkerd/linkerd2
- Answer: Yes, that's right

6. We will update Stable to use https://github.com/linkerd/linkerd2/releases/tag/stable-2.3.2 (or the latest Stable release)
- Answer: Yes, that's right

7. We will update head to use https://github.com/linkerd/linkerd2/commits/master (latest commit on master)
- Answer: Yes, that's right

8. We will update the build phase to use https://github.com/linkerd/linkerd2
- Answer: Yes, that's right

9. We will update the app-deploy phase to use https://github.com/linkerd/linkerd2
- Answer: Yes, that's right

**Comment by lixuna** [comment]
Closing as complete, Linkerd 2.x project details, release names and build status released to production on Wed, Sept 4th in v2.6.0 

Followup tickets to add `deploy` status, handle longer `Stable release name`

**Comment by lixuna** [comment]
<img width="738" alt="Screenshot 2019-09-06 19 24 59" src="https://user-images.githubusercontent.com/11701267/64467203-18dc8b00-d0dc-11e9-8258-2c3e6709f29b.png">
