### ISSUE TITLE
[CI Refactor] Create a cncf.ci K8s-infra provisioning CLI tool 

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#154]
**Feature Name:** 

- Create a cncf.ci K8s-infra provisioning CLI tool 

**Short Description:** 

- As part of the CI Refactoring EPIC #100  on cncf.ci, we will create a cncf.ci K8s-infra provisioning CLI tool
- the CLI tool will support kubespray and kind as plugins, starting with kubespray
- Prototype will be written using Ruby language

**Visual representation of CI Refactoring EPIC:** 

<img width="593" alt="Screenshot 2019-06-24 16 56 32" src="https://user-images.githubusercontent.com/11701267/60054757-0fc54b80-96a1-11e9-9ff5-f894b739bd2d.png">

**Input**
- declarative configuration for cluster
- architecture, K8s release, nodes, roles
- example at #226 (comment)

**Output summary of cluster configuration**
- target servers (hosts) IPs
- Roles (master or worker) of servers
- summary of number of worker and master nodes
- K8s release
- machine architecture

**Tasks**

- [x]  planning
- [ ]  implementation
    - [ ]  Infra-provisioning Tasks: https://github.com/crosscloudci/infra-provisioning
    - [ ]  K8s-infra Tasks: https://github.com/crosscloudci/k8s-infra   
- [ ]  QA
- [ ]  promote to production

**Comment by lixuna** [comment]
Status: needs planned

**Comment by lixuna** [comment]
This task has been completed, as a pre-req for #181 (in progress)
