### ISSUE TITLE
[Adding new project] External builds: Initial CI Proxy with end point returning mock build status for a commit ref or tag

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#176]
## Feature Name:
- External builds: Initial CI Proxy with end point returning mock build status for a commit ref or tag

## Short Description:

Stand alone CI Proxy service which will return build results for a specific commit ref or tag which are passed to it via API call. Initially mock/fake status results will be returned.

A test project, called testproj, will be used. It will consist of a test repo (github.com/crosscloudci/testproj/), global configuration, configuration repo (testproj-configuration), ci proxy configuration, a gitlab pipeline and mock build status data.

## Tasks: 
- [x]   Planning
- [x]   Implementation
     - [x]   Global Configuration Tasks
     - [x]   Per-project Configuration Tasks
     - [x]   GitLab Configuration Tasks
     - [x]   Status Repo Tasks
     - [x]   CI-Dashboard Tasks
     - [x]   CI Proxy Tasks
- [ ]   QA / Integration

## Acceptance Criteria: https://github.com/crosscloudci/crosscloudci/issues/176#issuecomment-520601825

**Comment by lixuna** [comment]
### Acceptance Criteria: 

_Setup Steps_
- [ ]  update ciproxy config to set citest as cisystem type https://github.com/crosscloudci/testproj-configuration/blob/76764e7841c570bcaa6869c1e50e9e93ad9abdaf/cncfci.yml#L10
- [ ] Redeploy CI Status Repo for the environment to test.  Eg. devapi.cncf.ci / gitlab pipeline for ci_status_repo
- [ ] Wait for CI dashboard to show N/A badges for the testproject

_Test Steps_
- [ ]  Run the Trigger client 
    - [ ]  Gitlab project pipeline for test project should run
- [ ]  Gitlab project pipeline uses a client (eg. curl)  to call CI Proxy requesting build status
    - [ ]  Passes required options (eg. arch, project name)
- [ ]  CI Proxy determines CI plugin to use for project (eg. `citest` for test project)
- [ ]  CI Proxy retrieves mock build status of citest builds which should always be passing
   - [ ] Response is returned to calling client
- [ ] Gitlab pipeline should print build status retrieved from the CI Proxy
- [ ]  Test project should be displayed on dev.cncf.ci under ONAP
- [ ]  Under Test project’s “Build” column, the build status badge should "success"
    - [ ]  Display stable build status
    - [ ]  Display head build status
- [ ]  Clicking on the Test Project’s stable build badge should go to the Gitlab build stable pipeline 
- [ ]  Clicking on the Test Project’s head build badge should go to the Gitlab build head pipeline 
- [ ]  App deploy badges should show N/A
- [ ]  Test badges should show N/A

**Comment by lixuna** [comment]
Closing ticket: Promoted to production on Tue, Sept 3 in v2.6.0
