### ISSUE TITLE
[Adding new projects] External builds: Create an external Plugin for Travis CI

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#177]
## Feature Name:
- External builds: Create an external Plugin for Travis CI 

## Short Description:

- To create a Travis CI plugin to use with the new CI Proxy
- A/C show status on dev/staging (DO NOT ENABLE “test project” on production)
- To use the test project from Ticket 250 to integrate the plugin with CI proxy
- goal of showing external CI system’s build status for stable build and head build on x.cncf.ci

## Tasks: 
- [x]   Planning
- [x]   Implementation
     - [x]   Global Configuration Tasks
     - [x]   Per-project Configuration Tasks
     - [x]   GitLab Configuration Tasks
     - [x]   Status Repo Tasks
     - [x]   CI-Dashboard Tasks
     - [x]   CI Proxy Tasks
     - [x]   CI Plugin Tasks

- [x]   QA / Integration

## Acceptance Criteria: https://github.com/crosscloudci/crosscloudci/issues/177#issuecomment-520610389

**Comment by lixuna** [comment]
### Acceptance Criteria: 

- [ ]  Use cncfci test project “testproj” > https://gitlab.dev.cncf.ci/cncfci/testproj 
- [ ]  Automatically run builds for the test project on Travis CI
    - [ ]  Using github hooks to automate builds to new commits and new releases
- [ ]  Run the Trigger client 
    - [ ]  Gitlab project pipeline for test project should run
- [ ]  Gitlab project pipeline uses a client (eg. curl)  to call CI Proxy requesting build status
    - [ ]  Passes required options (eg. arch, project name)
- [ ]  CI Proxy determines CI plugin to use for project (eg. Travis for test project)
- [ ]  CI Proxy retrieves status of Travis builds and passes status to calling client
    - [ ]  Status is returned immediately based on current status of Travis job.
    - [ ]  No waiting if job is still running. 
- [ ]  Test project should be displayed on dev.cncf.ci under ONAP
- [ ]  Under Test project’s “Build” column, the build status badge should display Travis build status “running/success/failed/N/A”
    - [ ]  Display stable build status
    - [ ]  Display head build status
- [ ]  Clicking on the Test Project’s stable build badge should go to the Gitlab build pipeline 
    - [ ]  URLs pointing to Travis CI build job should display in GitLab console log
    - [ ]  open Travis CI build job URL, the build status that is displayed on Travis should match the build status that is displaying on x.cncf.ci
- [ ]  Clicking on the Test Project’s head build badge should go to the Gitlab build pipeline 
    - [ ]  URLs pointing to Travis CI build job should display in GitLab console log
    - [ ]  open Travis CI build job URL, the build status that is displayed on Travis should match the build status that is displaying on x.cncf.ci
- [ ]  App deploy badges should show N/A
- [ ]  Test badges should show N/A

**Comment by lixuna** [comment]
Closing ticket: Promoted to production on Tue, Sept 3 in v2.6.0
