### ISSUE TITLE
[Adding new project] Build status: Add plugin versioning to CI Proxy

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#190]
**Feature Name:** 

- Build status: Add versioning to CI proxy plugins

**Short Description:** 

- describe/define the version of the CI proxy plugin 
- support specifying the version of the CI Proxy plugin in the plugin configuration file

**Location/URL:** 

- https://github.com/crosscloudci/ex_ci_proxy
- https://github.com/crosscloudci/ex_ci_proxy/blob/master/ci_plugins.yml

**Tasks:**
- [x]   Planning 
- [x]   CI proxy tasks
- [ ]   QA on staging
- [ ]   promote to production

## Acceptance Criteria: https://github.com/crosscloudci/crosscloudci/issues/190#issuecomment-527633301

**Comment by lixuna** [comment]
### Acceptance Criteria: CI Proxy retrieves specified version of Travis plugin



Prereq:
- Working Docker setup
- Reference repo docs https://github.com/crosscloudci/ex_ci_proxy#docker

- [x] Clone the CI Proxy repo
- [x] Change the ref used for the travis plugin in ci_plugins.yml
     - eg. `ref: 'master`' => `ref 'staging'`
- [x] Follow documentation to build the CI Proxy Docker image -  https://github.com/crosscloudci/ex_ci_proxy#docker
- [x] Follow documentation to get a shell in the docker image
     - Example: docker exec -ti crosscloud/ciproxy:latest /bin/bash 
- [x] Go into the plugin folder under ci_plugins
- [x] Type `git status`
- [x] The output should have the message `HEAD detached at ` followed by the ref specified in the configuration.  (eg. "production" or "v0.1.0")

**Comment by lixuna** [comment]
Closing ticket as completed, part of v2.6.0 release to production
