### ISSUE TITLE
[Issue] Build and deploy did not run as expected at 3am ET

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#191]
**Issue Name:**

- Build and deploy did not run as expected at 3am ET

**Short Description:**

- cncf.ci says "Last updated: 13 hours ago" when I would expect it to say "7 hours ago"
- cncf.ci shows no Test Environment, no release names, all N/A badges

**Screenshot:**
<img width="1098" alt="Screenshot 2019-09-04 09 32 55" src="https://user-images.githubusercontent.com/11701267/64264503-03f2d280-cef7-11e9-9d3b-6444d5f0d7a3.png">

**Tasks:**

- [x]  Review logs
- [x]  Locate cause of issue
- [x]  Resolve cause of issue
- [x]  QA
- [x]  Run build and deploy on cncf.ci

**Comment by lixuna** [comment]
Update: the issue with the 3am chron job has been resolved. cncf.ci is showing "Last updated: 5 hours ago" as expected:

<img width="994" alt="Screenshot 2019-09-05 10 21 11" src="https://user-images.githubusercontent.com/11701267/64355551-0a507f80-cfc7-11e9-8587-665f041b80eb.png">

**Comment by denverwilliams** [comment]
@lixuna @taylor  Items required to fix.

1. Trigger-client changes were promoted to production https://github.com/crosscloudci/crosscloudci-trigger/pull/31 but hadn't been pulled down onto the production runner.

2. The testproj is set to false in the global configuration on production https://github.com/crosscloudci/cncf-configuration/blob/production/cross-cloud.yml#L230 but the trigger-client is not smart enough to check this first and will still attempt to parse the configuration_repo, and if it's not found it will fail - A production/configuration branch for testproj needed to be created.

3. Secrets variables hadn't been added on to the Gitlab Mirror/Project for Linkerd2.x.
