### ISSUE TITLE
[Adding new projects] External builds: Create an external Plugin for Circle CI

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#194]
## Feature Name:
- External builds: Create an external Plugin for Circle CI 

## Short Description:

- To create a Circle CI plugin to use with the CI Proxy
- A/C show status on dev/staging (DO NOT ENABLE “test project” on production)
- To use the test project from Ticket 250 to integrate the plugin with CI proxy
- goal of showing external CI system’s build status for stable build and head build on x.cncf.ci

## Tasks: 
- [x]   Planning
- [x]   Implementation
     - [x]   Global Configuration Tasks
     - [x]   Per-project Configuration Tasks
     - [x]   GitLab Configuration Tasks
     - [x]   Status Repo Tasks
     - [x]   CI-Dashboard Tasks
     - [x]   CI Proxy Tasks
     - [x]   CI Plugin Tasks

- [x]   QA / Integration

## Acceptance Criteria: Based on (Travis CI) https://github.com/crosscloudci/crosscloudci/issues/177#issuecomment-520610389

**Comment by lixuna** [comment]
Closing issue as completed (Circle CI integration works w/ testproj, available for use in adding new project build status)
