### ISSUE TITLE
[Adding new projects] External builds: Create an external Plugin for GitHub Actions

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#197]
## Feature Name:
- External builds: Create an external Plugin for GitHub CI 

## Short Description:
- Create a GitHub CI plugin to use with the CI Proxy
- Show testproj's external CI system’s build status for stable build and head build on x.cncf.ci

## Tasks: 
- [ ]   Planning
- [ ]   Implementation
     - [ ]   Global Configuration Tasks
     - [ ]   Per-project Configuration Tasks
     - [ ]   GitLab Configuration Tasks
     - [ ]   Status Repo Tasks
     - [ ]   CI-Dashboard Tasks
     - [ ]   CI Proxy Tasks
     - [ ]   CI Plugin Tasks

- [ ]   QA / Integration

**Comment by lixuna** [comment]
Closing issue as completed (GitHub Actions integration works w/ testproj, available for use in adding new project build status)
