### ISSUE TITLE
Apply for AWS Open Source Credits for cncf.ci 

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#201]
**Feature Name:** 

- Apply for AWS Open Source Credits for cncf.ci 

**Short Description:** 

- https://aws.amazon.com/blogs/opensource/aws-promotional-credits-open-source-projects/
- cncf.ci runs instances on AWS
- Apply for Open Source credits for AWS instances for cncf.ci

**Location/URL:** 

- Production: cncf.ci

---
---
## Tasks:
* [x] Calculate current usage https://calculator.s3.amazonaws.com/index.html#r=IAD&key=files/calc-a55433fdf91620720f471ad2d5856b336f520419&v=ver20191011qG
* [x]   Calculate projected usage https://calculator.s3.amazonaws.com/index.html#r=IAD&key=files/calc-1bbf057ead0b87f73c88f7cd2cc4e05ed31adc05&v=ver20191011qG
* [x]  Fill out form https://amazonmr.au1.qualtrics.com/jfe/form/SV_2fcLkH9J3fGWT3f?Q_CHL=qr
* [x]  wait 7-10 days for reply

**Comment by lixuna** [comment]
<img width="751" alt="Screenshot 2019-10-15 17 30 58" src="https://user-images.githubusercontent.com/11701267/66874925-35d56b00-ef72-11e9-96cb-2a244708ba48.png">

**Comment by dankohn** [comment]
Please don't do this. CNCF has plenty of AWS credits available that we can share with cncf.ci. But please reach out to me and explain why we need to use AWS instead of Packet.
