### ISSUE TITLE
[Adding new projects] Create initial "project"-configuration repos for CNCF-hosted Graduated and Incubating projects

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#210]
## Tasks:
* [x]  follow GitHub configuration steps in https://github.com/crosscloudci/crosscloudci/blob/master/CNCFCI_GITLAB_CONFIGURATION.md#github-project-configuration  
* [x]  find up-to-date list of Graduated/Incubating projects at https://landscape.cncf.io/format=card-mode&project=graduated,incubating
* [x]  create project-configuration for each Graduated/Incubating CNCF-project
* [x]  add LICENSE
* [x]  add README
* [x]  add cncfci.yml
* [x]  add .gitlab-ci.yml

**For Vitess (next on cncf.ci ROADMAP):**
* [x]  Make crosscloudci/projectname-configuration project -- https://github.com/crosscloudci/vitess-configuration
* [x]  edit the cncfci.yml
* [x]  edit .gitlab-ci.yml
* [x]  add LICENSE
* [x]  add README

**For containerd:**
* [x]  Make crosscloudci/projectname-configuration project -- https://github.com/crosscloudci/containerd-configuration
* [x]  edit the cncfci.yml
* [x]  edit .gitlab-ci.yml 
* [x]  add LICENSE
* [x]  add README

**For CloudEvents:**
* [x]  Make crosscloudci/projectname-configuration project -- https://github.com/crosscloudci/cloudevents-configuration
* [x]  edit the cncfci.yml
* [x]  edit .gitlab-ci.yml 
* [x]  add LICENSE
* [x]  add README

**For CNI:**
* [x]  Make crosscloudci/projectname-configuration project -- https://github.com/crosscloudci/cni-configuration
* [x]  edit the cncfci.yml
* [x]  edit .gitlab-ci.yml 
* [x]  add LICENSE
* [x]  add README

**For cri-o:**
* [x]  Make crosscloudci/projectname-configuration project -- https://github.com/crosscloudci/cri-o-configuration
* [x]  edit the cncfci.yml
* [x]  edit .gitlab-ci.yml 
* [x]  add LICENSE
* [x]  add README

**For etcd:**
* [x]  Make crosscloudci/projectname-configuration project -- https://github.com/crosscloudci/etcd-configuration
* [x]  edit the cncfci.yml
* [x]  edit .gitlab-ci.yml
* [x]  add LICENSE
* [x]  add README 

**For gRPC:**
* [x]  Make crosscloudci/projectname-configuration project -- https://github.com/crosscloudci/grpc-configuration
* [x]  edit the cncfci.yml
* [x]  edit .gitlab-ci.yml 
* [x]  add LICENSE
* [x]  add README

**For Harbor:**
* [x]  Make crosscloudci/projectname-configuration project -- https://github.com/crosscloudci/harbor-configuration
* [x]  edit the cncfci.yml
* [x]  edit .gitlab-ci.yml 
* [x]  add LICENSE
* [x]  add README

**For Helm:**
* [x]  Make crosscloudci/projectname-configuration project -- https://github.com/crosscloudci/helm-configuration
* [x]  edit the cncfci.yml
* [x]  edit .gitlab-ci.yml 
* [x]  add LICENSE
* [x]  add README

**For NATS:**
* [x]  Make crosscloudci/projectname-configuration project -- https://github.com/crosscloudci/nats-configuration
* [x]  edit the cncfci.yml
* [x]  edit .gitlab-ci.yml
* [x]  add LICENSE
* [x]  add README

**For Notary:**
* [x]  Make crosscloudci/projectname-configuration project -- https://github.com/crosscloudci/notary-configuration
* [x]  edit the cncfci.yml
* [x]  edit .gitlab-ci.yml
* [x]  add LICENSE
* [x]  add README

**For Open Policy Agent:**
* [x]  Make crosscloudci/projectname-configuration project -- https://github.com/crosscloudci/openpolicyagent-configuration
* [x]  edit the cncfci.yml
* [x]  edit .gitlab-ci.yml
* [x]  add LICENSE
* [x]  add README

**For OpenTracing:**
* [x]  Make crosscloudci/projectname-configuration project -- https://github.com/crosscloudci/opentracing-configuration
* [x]  edit the cncfci.yml
* [x]  edit .gitlab-ci.yml
* [x]  add LICENSE
* [x]  add README

**For Rook:**
* [x]  Make crosscloudci/projectname-configuration project -- https://github.com/crosscloudci/rook-configuration
* [x] edit the cncfci.yml
* [x] edit .gitlab-ci.yml
* [x] add LICENSE
* [x] add README

**For TiKV:**
* [x]  Make crosscloudci/projectname-configuration project -- https://github.com/crosscloudci/tikv-configuration
* [x]   edit the cncfci.yml
* [x]  edit .gitlab-ci.yml
* [x]    add LICENSE
* [x]  add README

**For TUF:**
* [x]  Make crosscloudci/projectname-configuration project -- https://github.com/crosscloudci/tuf-configuration
* [x]  edit the cncfci.yml
* [x]  edit .gitlab-ci.yml
* [x]   add LICENSE
* [x]  add README

**Comment by lixuna** [comment]
16 new per-project configuration repos are ready for collaboration. Closing this issue as done.
