### ISSUE TITLE
[Bugfix] Provisioning K8s Stable and Head fails on Arm

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#221]
**Feature Name:** 

- [Bugfix] Provisioning K8s Stable and Head fails on Arm

**Short Description:** 

- https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/216150
- https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/216154

```
NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/k8s-infra/lib/provisioner/kubespray/kubespray/cluster.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
node0                      : ok=266  changed=22   unreachable=0    failed=1   
node1                      : ok=204  changed=16   unreachable=0    failed=0   

cluster allocation failed
Uploading artifacts...
WARNING: ./data/: no matching files                
ERROR: No files to upload                          
ERROR: Job failed: exit code 1
```

**Location/URL:** 

- https://cncf.ci/

---

### Tasks:

- [ ]

**Comment by lixuna** [comment]
On https://cncf.ci/, Provisioning for K8s Stable + Arm has been resolved, https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/216383 works as expected.

However, Provisioning for K8s Head + arm is still showing Failed, see https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/216391

Provisioning for K8s Head + x86 is now showing “NO MORE HOSTS” as well, see
https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/216387

**Comment by lixuna** [comment]
Today, on https://cncf.ci/, Provisioning for all 4 Test Environments are showing failed: 

To do:

- [ ]  restart node for K8s Stable + x86, see https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/217788
- [ ]  restart node for K8s Head + x86, see https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/217796
- [ ]  restart node for K8s Stable + Arm, see https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/217792
- [ ]  restart node for K8s Head + Arm, see https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/217800

**Comment by lixuna** [comment]
Today, on https://cncf.ci/, Provisioning for all 4 Test Environments are showing failed: 

Same todos as previous comment
