### ISSUE TITLE
[BUG] provisioning fails on all test environments

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#227]
**Feature Name:** 

- [Bugfix] Provisioning K8s Stable and Head fails on Arm and x86

**Short Description:** 
- provisioning fails on all test environments
- https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/243922
- https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/243918
- https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/243914
- https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/243910

**Location/URL:** 

- https://cncf.ci/

---

### Tasks:
Implementation:
- [ ]   restart node for K8s Stable + x86
- [ ]   restart node for K8s Stable + Arm
- [ ]   restart node for K8s Head + Arm
- [ ]   restart node for K8s Head + x86

Testing: 
- [ ]   test on dev
- [ ]   test on staging
- [ ]   promote to production
