### ISSUE TITLE
[BUG] Provisioning fails on K8s Stable + x86, K8s head + x86 and K8s head + arm

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#229]
### [BUG] Provisioning fails on K8s Stable + x86, K8s head + x86 and K8s head + arm

**To Reproduce**
- see https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/271042
- see https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/271050
- see https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/271054

**Common Error message in logs**
`NO MORE HOSTS LEFT`

**Expected behavior**
- Provisioning shows `SUCCESS` on K8s Stable + x86, K8s head + x86 and K8s head + arm on cncf.ci

**Test Environment Configuration:**
 - K8s: Stable & Head
 - Architecture: x86 & Arm

**Section:**
- Test Environment

### Tasks:
Implementation:
- [ ]   restart node for K8s Stable + x86
- [ ]   restart node for K8s Head + Arm
- [ ]   restart node for K8s Head + x86

Testing: 
- [ ]   test on dev
- [ ]   test on staging
- [ ]   promote to production
