### ISSUE TITLE
[BUG] Provisioning fails on K8s Stable + x86, K8s head + x86,  K8s Stable + arm and K8s head + arm

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#231]
### [BUG] Provisioning fails on K8s Stable + x86, K8s head + x86,  K8s Stable + arm and K8s head + arm 

To Reproduce:
- see https://cncf.ci/
- see https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/279618 - cluster allocation failed
- see https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/279622 - cluster allocation failed
- see https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/279626 - cluster allocation failed
- see https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/279630 - cluster allocation failed

**Expected behavior**
- Provisioning shows `SUCCESS` on K8s Stable + x86, K8s head + x86, K8s Stable + arm, K8s head + arm on cncf.ci

**Test Environment Configuration:**
 - K8s: Stable & Head
 - Architecture: x86 & Arm

**Section:**
- Test Environment

### Tasks:
Implementation:
- [x]   restart node for K8s Stable + x86
- [x]   restart node for K8s Head +  x86
- [x]   restart node for K8s Stable + Arm
- [x]   restart node for K8s Head + Arm

Testing: 
- [ ]   test on dev
- [ ]   test on staging
- [ ]   promote to production

**Comment by agentpoyo** [comment]
Started off restating the nodes for head and stable for both amd64 and arm64 nodes.

**Comment by agentpoyo** [comment]
Digging into this issue, it is kubespray does not yet support lates k8s v1.20:

```
The error was: 'dict object' has no attribute 'v1.20'\n\nThe error appears to be in '/k8s-infra/lib/provisioner/kubespray/kubespray/roles/download/tasks/download_file.yml'
```

kubespray latest stable release on Oct 30th still uses default k8s version 1.18:  https://github.com/kubernetes-sigs/kubespray/releases/tag/v2.14.2
