### ISSUE TITLE
[04-12-2018] add GKE token authentication support to cross-cloud

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#45]
**Problem:**
 
- GKE badges are RED on cncf.ci

- client certificates no longer work with GKE Clusters for authorization

**Solution:** 

- use gcloud SDK to create kubeconfig with working authorization 

**Tasks:**
---

* [x]  install gcloud SDK 

* [x]  update provision.sh to use gcloud SDK

* [x]  Use gcloud cli to generate GKE kubeconfig

* [ ]  promote cross-cloud changes to production

**Comment by taylor** [comment]
GKE is now passing on cncf.ci
