### ISSUE TITLE
[Branding] EPIC: Update project name to "cncf ci"

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#94]
EPIC: Update project name to "cncf ci"
---

## GitHub: 

- [x] Update description to ``Integrating, testing, and deploying projects within the CNCF ecosystem. Results published daily to the CNCF CI Dashboard.``

## Artwork:

- [x]  Update name from cross-cloud ci to ``cncf.ci``

## Twitter: 

- [x]  Update profile from "Integrating, testing, and deploying projects within the #CNCF ecosystem across multiple cloud providers. Displaying test results to https://cncf.ci  🐙to ``Integrating, testing, and deploying projects within the #CNCF ecosystem. Displaying test results to https://cncf.ci `` 🐙
- [x]  Update name from cross-cloud ci to ``cncf.ci``
- [x]  Update @ from @crosscloudci to @cncfci ?

More TBD
