### ISSUE TITLE
[v2] EPIC: Responsive redesign for cncf.ci

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#99]
Feature: Responsive redesign for cncf.ci
---

## Short Description:
- Redesign cncf.ci to focus on projects:
  - To demonstrate the use of cloud native technologies
  - To promote CNCF projects and attract more projects to CNCF
  - To provide a third party, unbiased validation for CNCF projects
  - To support and contribute to a sustainable and scalable project ecosystem 
  - To get feedback from cloud native end users and projects
  - To compliment the landscape and trail map “Let’s see the CNCF projects in action”

## Key Features: 

- Highlight and validate CNCF’s Graduated and Incubating projects
- Increase collaboration with CNCF Project maintainers
- Accelerate adding new projects to cncf.ci
- Demonstrate provisioning Kubernetes releases on Bare Metal (Packet)

**Requirements:**

* [x] Show test environment w/ one version of Kubernetes at the top of the home screen (ie. Kubernetes, stable v1.13.3, deployed to Bare Metal (Packet)

* [x] Add selector for the Kubernetes release name (ie. Stable v1.13.1, Head c3e60b6, RC v1.13.3-RC)

* [ ] Add Sub-headers for project types: Graduated CNCF Projects, Incubating CNCF Projects, Linux Foundation Projects

* [ ] List projects in alphabetical order within their assigned sub-header

## Tasks: 
- [x] Create mocks for redesign
- [x] Implement redesign
- [ ] Merge to production on Mon, Feb 25, 2019
- [ ] Demo on Tue, Feb 26, 2019 in CI WG

**Comment by lixuna** [comment]
Closing this ticket

- #120 has been deferred to after the following: 
  - adding Arm, 
  - adding kubeadm, 
  - updating how to add a project to cncf.ci
